AWSTemplateFormatVersion: '2010-09-09'
Description: Basic interactive elements delivery sling
Parameters:
  App:
    Type: String
    Description: Application name
  Stack:
    Type: String
    Description: Stack name
  Stage:
    Type: String
    Description: Production stage
    AllowedValues:
      - PROD
      - CODE

Resources:
  InputBucket:
    Type: AWS::S3::Bucket
    Properties:
      Tags:
        - Key: App
          Value: !Ref App
        - Key: Stack
          Value: !Ref Stack
        - Key: Stage
          Value: !Ref Stage

  OutputBucket:
    Type: AWS::S3::Bucket
    Properties:
      Tags:
        - Key: App
          Value: !Ref App
        - Key: Stack
          Value: !Ref Stack
        - Key: Stage
          Value: !Ref Stage

  TranscodeCompletedTopic:
    Type: AWS::SNS::Topic
    Properties:
      Tags:
        - Key: App
          Value: !Ref App
        - Key: Stack
          Value: !Ref Stack
        - Key: Stage
          Value: !Ref Stage

  TranscodeFailedTopic:
    Type: AWS::SNS::Topic
    Properties:
      Tags:
        - Key: App
          Value: !Ref App
        - Key: Stack
          Value: !Ref Stack
        - Key: Stage
          Value: !Ref Stage

