name: Branch-build

on:
  pull_request:
    branches:
      - "*"

jobs:
  pullrequest:
    runs-on: ubuntu-latest
    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - run: make test
      - run: make prod

      - uses: actions/upload-artifact@v3
        with:
          name: simple-interactive-deliverables
          path: build/